export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REDIRECTED = 'REDIRECTED'
export const LOGOUT = 'LOGOUT'

export const GET_YEAR_SUCCESS = 'GET_YEAR_SUCCESS'
export const GET_MONTH_SUCCESS = 'GET_MONTH_SUCCESS'

export const CURRENT_YEAR = 2017

export const UPDATE_MONTHLY_DATA = 'UPDATE_MONTHLY_DATA'
export const ADD_EXPENCIVE = 'ADD_EXPENCIVE'
export const DELETE_EXPENCIVE = 'DELETE_EXPENCIVE'

